"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import {usePathname} from "next/navigation"


const navLinks =[
  {href: "/login", name: "Login"},
  {href: "/register", name: "Register"},
  {href: "/forgot-password", name: "Forgot Password"},
]


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by GH npx create next app and this layout is special reviews",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // get the current path
  const pathname = usePathname();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          {navLinks.map((link)=>{
          const isActive = pathname === link.href || 
          pathname.startsWith(link.href) && link.href !== "/";
            return(
              <Link href={link.href} key={link.name} 
              className={isActive ? "font-bold mr-4" 
              : 
              "text-blue-500 mr-4"}>
              {link.name}
              </Link>
            )
          })}
      
          {children}
        </div>
        <footer
          style={{
            color: "red",
            fontSize: "1.5rem",
            fontWeight: "bold",
            textAlign: "center",
            backgroundColor: "ghostwhite",
            padding: "1rem",
            
          }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
