import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by GH npx create next app",
};

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header
          style={{
            backgroundColor: "LightBlue",
            color: "grey",
            fontSize: "1.5rem",
            fontWeight: "bold",
            padding: "1rem"
          }}
        >
          <p>Header</p>
        </header>
        {children}
        <footer
          style={{
            color: "grey",
            fontSize: "1.5rem",
            fontWeight: "bold",
            textAlign: "center",
            backgroundColor: "ghostwhite",
            padding: "1rem",

          }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
